package:
  name: pypy
  version: 2.3

source:
  fn: pypy-2.3-src.tar.bz2
  url: https://bitbucket.org/pypy/pypy/downloads/pypy-2.3-src.tar.bz2
  md5: c93a8e47f3b3109af2f66d2bd766eb97

build:
  number: 0

requirements:
  build:
    - python
    - sphinx
    - zlib
    - bzip2
    - libffi
    - expat
    - pkg-config
    
about:
  home: http://pypy.org
  license: BSD
  summary: PyPy is a fast, compliant alternative implementation of the Python language.