package:
  name: setuptools
  version: "4.0.1"

source:
  url: https://pypi.python.org/packages/source/s/setuptools/setuptools-4.0.1.tar.gz
  fn: setuptools-4.0.1.tar.gz

  patches:
    - never_zip_safe.patch

build:
  number: 0

  track_features:
    - pypy

requirements:
  build:
    - python

  run:
    - python


about:
  home: https://pypi.python.org/pypi/setuptools
  license: PSF
