package:
  name: opt-python
  version: "2.7.6"

build:
  number: 0
  
requirements:
  build:
    - python 2.7.6.pypy.*

  run:
    - openssl
    - sqlite
    - system
    - tk
    - zlib
    - bzip2
    - libffi
    - expat
    - ncurses
    
    
about:
  home: http://pypy.org
  license: MIT
  summary: PyPy is a fast, compliant alternative implementation of the Python language.
