package:
  name: python
  version: "2.7.6.pypy.2.3.1"

source:
  fn: release-2.3.1.tar.bz2
  url: https://bitbucket.org/pypy/pypy/get/release-2.3.1.tar.bz2

build:
  number: 3
  
  features:
    - pypy

  track_features:
    - pypy

requirements:
  build:
    - opt-python
    - openssl
    - sqlite
    - system
    - tk
    - zlib
    - bzip2
    - libffi
    - expat
    - ncurses

  run:
    - openssl
    - sqlite
    - system
    - tk
    - zlib
    - bzip2
    - libffi
    - expat
    - ncurses
    
    
about:
  home: http://pypy.org
  license: MIT
  summary: PyPy is a fast, compliant alternative implementation of the Python language.
