package:
  name: cmake
  version: 3.0.1

source:
  fn: cmake-3.0.1.tar.gz
  url: http://www.cmake.org/files/v3.0/cmake-3.0.1.tar.gz

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
