package:
  name: numpy
  version: 1.0

source:
  git_url: https://bitbucket.org/pypy/numpy.git
  git_branch: master

build:
  number: 0

  track_features:
    - pypy

requirements:
  build:
    - python

  run:
    - python

about:
  home: http://pypy.org

  